[mainApp]
host = "127.0.0.1"
port = "80"

[log]
logFilePath = ""
logFileName = "blog.log"

[mysql]
host = "192.144.210.253"
port = "3306"
user = "root"
password = "Bao7102655"
protocol = "tcp"
database = "blog"