[mainApp]
host = "127.0.0.1"
port = "8081"

[log]
logFilePath = "log//"
logFileName = "blog.log"

[mysql]
host = "192.144.210.253"
port = "3306"
user = "root"
password = "Bao7102655"
protocol = "tcp"
database = "blog"

[github]
clientId = "389fcfe7392aea24002c"
clientSecret = "eeb80ef351222e070bc7aa235acf3af68ffafceb"